[package]
name = "multisig-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>, Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2018"
publish = false
[dependencies.multisig]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.4"
