[package]
name = "transaction"
version = "0.0.0"
authors = ["dorin-iancu <dorin.iancu@multiversx.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"
[dependencies.eth-address]
path = "../eth-address"

[dependencies.multiversx-sc]
version = "0.43.4"
