name: CI

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main, feat/* ]
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  id-token: write
  issues: write
  discussions: write
  pull-requests: write
  statuses: write

jobs:
  contracts:
    - name: Check Rust toolchain version
      run: rustc --version
      secrets:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Contracts
      uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v3.1.0
      with:
        rust-toolchain: stable
        vmtools-version: v1.5.24
      secrets:
        token: ${{ secrets.GITHUB_TOKEN }}

