[package]
name = "token-module"
version = "0.0.0"
authors = ["dorin-iancu <dorin.iancu@multiversx.com>"]
edition = "2018"

[dependencies.multiversx-sc]
version = "=0.43.5"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.43.5"
